--库存组织

SELECT A.ORGANIZATION_CODE, A.ORGANIZATION_ID, A.ORGANIZATION_NAME
  FROM APPS.ORG_ORGANIZATION_DEFINITIONS A, APPS.MTL_PARAMETERS MP
 WHERE A.ORGANIZATION_ID = MP.ORGANIZATION_ID
   AND A.ORGANIZATION_ID <> MP.MASTER_ORGANIZATION_ID
